Frontend:
  impl: LoadStoreTrace
  # impl: SimpleO3
  clock_ratio: 8
  # num_expected_insts: 200000
  # llc_capacity_per_core: 1MB
  # llc_num_mshr_per_core: 1
  path: ../ld_st_trace.trace
  # traces:
    # - ../traces/low-mem-intensity.trace
    # - ../traces/low-mem-intensity.trace
    # - ../traces/high-mem-intensity.trace
    # - ../traces/low-mem-intensity.trace

  Translation:
    impl: RandomTranslation
    max_addr: 2147483648

MemorySystem:
  impl: GenericDRAM
  clock_ratio: 3

  DRAM:
    impl: DDR4
    org:
      preset: DDR4_4Gb_x8
      channel: 4
      rank: 2
    timing:
      preset: DDR4_2400R

  Controller:
    impl: Generic
    Scheduler:
      impl: FCFS
    RefreshManager:
      impl: AllBank
    RowPolicy:
      impl: OpenRowPolicy
      cap: 4
    plugins:
      - ControllerPlugin:
          impl: TraceRecorder
          path: ./example_dram.trace

  AddrMapper:
    impl: RoBaRaCoCh