Frontend:
  impl: SimpleO3
  clock_ratio: 8
  num_expected_insts: 20000000
  llc_capacity_per_core: 1KB # Should be set as no cache, but this is a workaround
  traces:
     - ../traces/low-mem-intensity.trace
     - ../traces/low-mem-intensity.trace
     - ../traces/high-mem-intensity.trace
     - ../traces/high-mem-intensity.trace
     - ../traces/high-mem-intensity.trace
     - ../traces/high-mem-intensity.trace

  Translation:
    impl: RandomTranslation
    max_addr: 2199015689679


MemorySystem:
  impl: GenericDRAM
  clock_ratio: 3

  DRAM:
    impl: DDR4
    org:
      preset: DDR4_8Gb_x8
      channel: 2
      rank: 1
    timing:
      preset: DDR4_2400R

  Controller:
    impl: Generic
    Scheduler:
      impl: BLISS_CTR
    RefreshManager:
      impl: AllBank
    RowPolicy:
      impl: OpenRowPolicy
      cap: 4
    plugins:
      - ControllerPlugin:
          impl: BLISS
          blacklist_thresh: 4
          unblacklist_cycles: 10000


  AddrMapper:
    impl: RoBaRaCoCh